config/routes.rb
Rails.application.routes.draw do

  get 'relationship/create'
  get 'relationship/destroy'
  get 'create/destroy'
  root 'home#top'
  
  devise_for :companies
  devise_for :colleges

  get 'home/top'
  
  get '/colleges/:id', to: 'colleges#show', as: 'college'
  get '/companies/:id', to: 'companies#show', as: 'company'
  get '/companies', to: 'companies#index', as: 'company2'
  get '/users/:id', to: 'users#show', as: 'user'
  # get 'products/index'
  # get 'products/new'
  # post 'products/create'
  # post 'products/all_destroy'
  # get 'products/:id' => 'products#show'
  # get 'products/:id/edit' => 'products#edit'
  # post 'products/:id/update' => 'products#update'
  # post 'products/:id/destroy' => 'products#destroy'
  
  resources :products do
    resources :likes,  only: [:create, :destroy]
    
    resources :comments, only: [:create]
    resources :pictures, only: [:create]
    
    member do
      get :matching_products
    end
    
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :colleges do
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :companies do
     member do
      get :matching_companies
    end
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :matchings, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes
  has_many :relationships
  has_many :followings , through: :relationships, source: :college
  # has_many :followings , through: :relationships
  # マッチングリレーション
  has_many :matchings
  has_many :matching_products, through: :matchings, source: :product
  has_many :comments
 
  def follow(other_college)
    unless self == other_college
      self.relationships.find_or_create_by(college_id: other_college.id)
    end
  end
  
  def unfollow(other_college)
    relationship = self.relationships.find_by(college_id: other_college.id)
    relationship.destroy if relationship
  end
  
  def following?(other_college)
   self.followings.include?(other_college)
  end
  
  def match_product(product)
    unless self == product
      self.matchings.find_or_create_by(product_id: product.id)
    end  
  end 
  
  def matching?(product)
    self.matching_products.include?(product)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    @company = Company.find_by(id: params[:id])
    @matchings = Matching.new
    @match_product = @company.matching_products
  end
  
  def index
    @companies=Company.all
  end
  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_companies.html.erb
<% companies.each do |company| %>
  <%= image_tag company_avater_url(company),class: 'text-center'%>
  <%= link_to company.name,company_path(company)%>
<% end %>

app/views/companies/index.html.erb
<p>
  <%= render "companies", companies: @companies %>
</p>

app/views/companies/show.html.erb
<div class="container">
    <p class="text-center">  
      <%= image_tag company_avater_url(@company),class: 'text-center'%>
    </p>
    <h1 class="text-center"><%= @company.name %>会社</h1>

    <% if current_company == @company %>
      <div class="match_product">
        <h3>リクエスト送信済み投稿</h2>
        <% @match_product.each do |match_product| %>
          <%= link_to match_product.title, product_path(match_product.id) %>
        <% end %>
      </div>  
      <%= link_to "プロフィール設定", edit_company_registration_path(current_company.id) %>
    <% end %>  
    <p><%= @company.description %></p>
    
        <% unless current_company %>
          <div class="follow">
            <%= render 'relationships/follow_button',company: @company %>
          </div>
        <% end %>
    
</div>