config/routes.rb
Rails.application.routes.draw do

  get 'relationship/create'
  get 'relationship/destroy'
  get 'create/destroy'
  root 'home#top'
  
  devise_for :companies
  devise_for :colleges

  get 'home/top'
  
  get '/colleges/:id', to: 'colleges#show', as: 'college'
  get '/companies/:id', to: 'companies#show', as: 'company'
  get '/companies', to: 'companies#index', as: 'company2'
  get '/users/:id', to: 'users#show', as: 'user'
  # get 'products/index'
  # get 'products/new'
  # post 'products/create'
  # post 'products/all_destroy'
  # get 'products/:id' => 'products#show'
  # get 'products/:id/edit' => 'products#edit'
  # post 'products/:id/update' => 'products#update'
  # post 'products/:id/destroy' => 'products#destroy'
  
  resources :products do
    resources :likes,  only: [:create, :destroy]
    
    resources :comments, only: [:create]
    resources :pictures, only: [:create]
    
    member do
      get :matching_products
    end
    
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :colleges do
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :companies do
     member do
      get :matching_companies
    end
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :matchings, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/product.rb
class Product < ApplicationRecord
  
  has_many :comments
  has_many :pictures
  # マッチングリレーション
  has_many :matchings
  has_many :matching_companies, through: :matchings, source: :company
  belongs_to :college
  has_many :likes, -> { order(created_at: desc) },dependent: :destroy
  
    def liked_by(company)
        Like.find_by(company_id: company.id,product_id: id)
    end
  
    def like_by(college)
        Like.find_by(college_id: college.id,product_id: id)
    end
  
        
  
  # バリデーション
  validates :title, presence: true, length: { maximum: 70 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :price, presence: true,
                    numericality: { only_integer: true}
                    
  default_scope -> { order(created_at: :desc) }
  accepts_nested_attributes_for :pictures
  
  # default_scope -> { order(created_at: :desc) }
  # scope :search_by_keyword, -> (keyword) {
  #   # Blog.where(['title LIKE ? OR content LIKE ?', "%#{keyword}%", "%#{keyword}%"])
  #   # where("products.title LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%") if keyword.present?
  #   where(["products.title LIKE ? OR products.content LIKE ?", "%#{keyword}%", "%#{keyword}%"]) if keyword.present?
  # }
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_college!, only: [:new, :create, :edit, :update, :destroy]
  # before_action :authenticate_company!, only: [:show]
  before_action :require_current_college, only: [:edit, :update, :destroy]
  protect_from_forgery except: :create
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    3.times { @product.pictures.build }
    # @product.pictures.build
  end

  def create
    @product = current_college.products.new(product_params)

    if @product.save
      flash[:success] = "投稿しました"
      redirect_to products_path
    else
      flash.now[:danger] = "投稿に失敗しました"
      render("/products/new")
    end
  end
  
  def edit
    @product = Product.find_by(id: params[:id])
  end
  
  def update
    @product = Product.find_by(id: params[:id])
    if @product.update(product_params)
      flash[:success] = "保存しました"
      redirect_to products_path
    else
      flash.now[:danger] = "保存できませんでした"
      render :edit
    end
  end
  
  def show
    @product = Product.find_by(id: params[:id])
    @comments = @product.comments
    @comment = Comment.new
  end
  
  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy
    flash[:warning] = "削除しました"
    redirect_to products_path
  end

  # def all_destroy
  #   @products = Product.all
  #   @products.each do |product|
  #     product.destroy
  #   end
  #   flash[:warning] = "すべて削除しました"
  #   redirect_to("/products/index")
  # end
  
  private
    
    def product_params
      params.require(:product).permit(:title, :content, :price, pictures_attributes: [:id, :product_id, image: []])
      # params.require(:product).permit(:title, :content, :price, pictures_attributes: [:image])
    end
  
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products.html.erb
<% products.each do |product| %>
                
  <%=link_to  product_path(product.id) do %>
      <div class="card">
          <div class="card-body">
              <!--<h2 class="card-title"><%#= link_to product.college_id, college_path(product.college_id)  %></h2>-->
              <%= image_tag college_avater_url(product.college),class: 'text-center'%>
              <h2 class="card-title">タイトル：<%= product.title %></h2>
              <p class="card-text">概要：<%= product.content %></p>
              <p class="card-text">￥<%= product.price %></p>
          </div>
      </div>
  <% end %>

<%end%>

app/views/products/edit.html.erb
<div class="container">
    <div class="row">
        <div class="offset-md-2 col-md-8">
            <br>
            <h2>編集</h2>
            
            <%= form_for(@product) do |f| %>
            
              <%= render 'layouts/error_messages', product: @product %>
                  <%= f.label :title %>
                  <%= f.text_field :title, placeholder: "○○字以内", class: 'form-control' %>
                  
                  <% if false %>
                  <div class="form-group">
                    <%= f.fields_for :pictures do |picture| %>
                      <%= picture.file_field :image_url, multiple: true %>
                    <% end %>  
                  </div>  
                  <% end %>
            
                  <%= f.label :price %>
                  <%= f.text_field :price, class: 'form-control' %>
                  
                  <div class="field">
                    <%= f.label :content %>
                    <%= f.text_area :content, placeholder: "説明", class: "form-control" %>
                  </div>
                  <%= f.submit "更新", class: "btn btn-primary col-xs-12 col-md-offset-3 col-md-6", data: { disable_with: "送信中..." } %>
              <% end %> 
            
            <% if false %>
            <%= form_tag("update",{method: "post"}) do %>
                <br><br><br>
                <p>タイトル</p>
                <input type="text" name="title" class="form-control" value="<%=@product.title%>">
                <br>
                <p>値段</p>
                <input type="text" name="price" class="form-control" value="<%=@product.price%>">
                <br>
                <p>本文</p>
                <textarea name="content" class="form-control" rows="30"><%=@product.content%></textarea>
                <br>
                <input type="submit" class="btn btn-primary" value="送信">
            <%end%>
            <% end %>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="offset-md-2 col-md-8">
            <br>

            <%#= link_to("[開発者用]すべて削除","all_destroy",method: "post",class: "btn btn-primary") %>
            <br><br><br>
            <% @products.each do |product| %>
            
                <%=link_to("/products/#{product.id}") do %>
                    <div class="card">
                        <div class="card-body">
                            <h2 class="card-title"><%= product.title %></h2>
                            <p class="card-text"><%= product.content %></p>
                            <p class="card-text">￥<%= product.price %></p>
                        </div>
                    </div>
                <% end %>
                
            <%end%>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="container">
    <div class="row">
        <div class="offset-md-2 col-md-8">
            <br>
            <h2>新規プロダクト作成</h2>
            
            <%= form_for(@product, :url => {:controller => :products, :action => :create}) do |f| %>
            
            <%= render 'layouts/error_messages', product: @product %>
                <%= f.label :title %>
                <%= f.text_field :title, placeholder: "○○字以内", class: 'form-control' %>
                
                <div class="form-group">
                  <!--picturesテーブル内のimageカラムに影響させることを指定-->
                  <%= f.fields_for :pictures, @product.pictures do |picture| %>
                    <%= picture.file_field :image, multiple: true %>
                  <% end %>  
                </div>  
                
                <%= f.label :price %>
                <%= f.text_field :price, class: 'form-control' %>
                
                <div class="field">
                  <%= f.label :content %>
                  <%= f.text_area :content, placeholder: "説明", class: "form-control" %>
                </div>
                <%= f.submit "投稿する", class: "btn btn-primary col-xs-12 col-md-offset-3 col-md-6", data: { disable_with: "送信中..." } %>
            <% end %> 
              
        </div>
    </div>
</div>

app/views/products/show.html.erb
<h5><%= @product.title %>の詳細ページ<h5>
<div class="container">
  <div class="offset-md-3 col-md-6">
     <div class="card">
        <div class="card-header"><h2><%= @product.title %></h2></div>
        <div class="card-body">
          <%= link_to @product.college.name, college_path(@product.college.id)%>
          <%= render "matchings/match_button", product: @product %>
          <p class="text-danger">￥<%= @product.price %></p>
          <%#= image_tag @product.pictures.image.url %>
          <% if  @product.college == current_college %>
            <%= link_to("編集","/products/#{@product.id}/edit") %>
            <%= link_to("削除",@product,{method: "delete"}) %>
          <% end %>
          <br><br>
            <% if current_company.present? %>
              <div id="like-icon-post-<%= @product.id.to_s %>">
                  <% if @product.liked_by(current_company).present?%>
                    <%= link_to "",product_like_path(@product.id, @product.liked_by(current_company)),method: :DELETE, class: "fa fa-2x fa-heart"%>
                      <% else %>
                    <%= link_to "",product_likes_path(@product),method: :POST, class: "fa fa-2x fa-heart-o"%>
                  <% end %>
              </div>
            <% else %>
               <div id="like-icon-post-<%= @product.id.to_s %>">
                    <% if @product.like_by(current_college).present?%>
                      <%= link_to "",product_like_path(@product.id, @product.like_by(current_college)),method: :DELETE, class: "fa fa-2x fa-heart"%>
                          <% else %>
                      <%= link_to "",product_likes_path(@product),method: :POST, class: "fa fa-2x fa-heart-o"%>
                    <% end %>
                </div>
              </div>
            <% end %> 
              <%= @product.likes_count%>
            <div class="product-content">
              <p>投稿内容</p>  
              <p><%= @product.content %></p>
            </div>
      </div>
            
            <!--ここからコメント-->
            <%= form_for [@product, @comment] do |f| %>
                <% if @comment.errors.any? %>
                    <div id="error_explanation">
                      <ul>
                        <% @comment.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
              <%= f.text_area :content %>
              <br>
              <%= f.submit 'コメントする' %>
            <% end %>
            <ul class="comments">
            <li>
                <% @comments.each do |comment| %>
                
                    <% if comment.college %>
                    <div class="college_comment" >
                        <%= link_to comment.college.name, college_path(comment.college_id) %>
                    </div>    
                    <% elsif comment.company %>
                    <div class="company_comment">
                        <%= link_to comment.company.name, company_path(comment.company_id) %>
                    </div>    
                    <% end %>
                    <%= comment.content %>
                <% end %>
            </li>    
            </ul>
    </div>
</div>