config/routes.rb
Rails.application.routes.draw do

  get 'relationship/create'
  get 'relationship/destroy'
  get 'create/destroy'
  root 'home#top'
  
  devise_for :companies
  devise_for :colleges

  get 'home/top'
  
  get '/colleges/:id', to: 'colleges#show', as: 'college'
  get '/companies/:id', to: 'companies#show', as: 'company'
  get '/companies', to: 'companies#index', as: 'company2'
  get '/users/:id', to: 'users#show', as: 'user'
  # get 'products/index'
  # get 'products/new'
  # post 'products/create'
  # post 'products/all_destroy'
  # get 'products/:id' => 'products#show'
  # get 'products/:id/edit' => 'products#edit'
  # post 'products/:id/update' => 'products#update'
  # post 'products/:id/destroy' => 'products#destroy'
  
  resources :products do
    resources :likes,  only: [:create, :destroy]
    
    resources :comments, only: [:create]
    resources :pictures, only: [:create]
    
    member do
      get :matching_products
    end
    
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :colleges do
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :companies do
     member do
      get :matching_companies
    end
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :matchings, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :likes
  # has_many :pictures, inverse_of: :college
  has_many :followings , through: :relationships, source: :company
  has_many :relationships
  has_many :comments
  # scope :search_by_keyword, -> (keyword) {
  #   where("colleges.name LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%") if keyword.present?
  # }
 
  
  def follow(other_company)
    unless self == other_company
      self.relationships.find_or_create_by(company_id: other_company.id)
    end
  end
  
  def unfollow(other_company)
    relationship = self.relationships.find_by(company_id: other_company.id)
    relationship.destroy if relationship
  end
  
  def following?(other_company)
    self.followings.include?(other_company)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :college, optional: true
  belongs_to :company, optional: true
  belongs_to :product
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes
  has_many :relationships
  has_many :followings , through: :relationships, source: :college
  # has_many :followings , through: :relationships
  # マッチングリレーション
  has_many :matchings
  has_many :matching_products, through: :matchings, source: :product
  has_many :comments
 
  def follow(other_college)
    unless self == other_college
      self.relationships.find_or_create_by(college_id: other_college.id)
    end
  end
  
  def unfollow(other_college)
    relationship = self.relationships.find_by(college_id: other_college.id)
    relationship.destroy if relationship
  end
  
  def following?(other_college)
   self.followings.include?(other_college)
  end
  
  def match_product(product)
    unless self == product
      self.matchings.find_or_create_by(product_id: product.id)
    end  
  end 
  
  def matching?(product)
    self.matching_products.include?(product)
  end

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :product
    belongs_to :company,optional: true
    belongs_to :college,optional: true
    counter_culture :product
        
end

app/models/matching.rb
class Matching < ApplicationRecord
  belongs_to :product
  belongs_to :company
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :product
    # belongs_to :college, inverse_of: :pictures
    
    mount_uploaders :image, PictureUploader
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :pictures
end

app/models/product.rb
class Product < ApplicationRecord
  
  has_many :comments
  has_many :pictures
  # マッチングリレーション
  has_many :matchings
  has_many :matching_companies, through: :matchings, source: :company
  belongs_to :college
  has_many :likes, -> { order(created_at: desc) },dependent: :destroy
  
    def liked_by(company)
        Like.find_by(company_id: company.id,product_id: id)
    end
  
    def like_by(college)
        Like.find_by(college_id: college.id,product_id: id)
    end
  
        
  
  # バリデーション
  validates :title, presence: true, length: { maximum: 70 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :price, presence: true,
                    numericality: { only_integer: true}
                    
  default_scope -> { order(created_at: :desc) }
  accepts_nested_attributes_for :pictures
  
  # default_scope -> { order(created_at: :desc) }
  # scope :search_by_keyword, -> (keyword) {
  #   # Blog.where(['title LIKE ? OR content LIKE ?', "%#{keyword}%", "%#{keyword}%"])
  #   # where("products.title LIKE :keyword", keyword: "%#{sanitize_sql_like(keyword)}%") if keyword.present?
  #   where(["products.title LIKE ? OR products.content LIKE ?", "%#{keyword}%", "%#{keyword}%"]) if keyword.present?
  # }
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :college
    belongs_to :company
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :college
    belongs_to :company
end

app/helpers/application_helper.rb
module ApplicationHelper
    # def avater_url(college)
    #   if current_college
    #     return college.college_image unless college.college_image.nil?
    #     gravatar_id = Digest::MD5::hexdigest(college.email).downcase
    #     "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
    #   elsif current_company
    #     return company.company_image unless company.company_image.nil?
    #     gravatar_id = Digest::MD5::hexdigest(company.email).downcase
    #     "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
    #   end
    # end 
    
    # userはログインしている方がcollegeかcompanyかで変わる
    def college_avater_url(college)
        # collegeでログインしている場合は、user=@collegeが入り、そこにcollege_imageを適用する
        return college.college_image unless college.college_image.nil?
        gravatar_id = Digest::MD5::hexdigest(college.email).downcase
        "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
    end
    
    def company_avater_url(company)
      return company.company_image unless company.company_image.nil?
      gravatar_id = Digest::MD5::hexdigest(company.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
    end
    
end

app/helpers/college_helper.rb
module CollegeHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/create_helper.rb
module CreateHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_before_navbar.html.erb
<!--ログイン前-->
<%= link_to("大学の方はこちら","/colleges/sign_up", class: "nav-link") %>

<%= link_to("企業の方はこちら","/companies/sign_up", class: "nav-link") %>

app/views/layouts/_college_navbar.html.erb
<li class="nav-item">
  <%= link_to("プロダクトを投稿","/products/new",class: "nav-link") %>
</li>

<li class="nav-item">
	<%= link_to '企業一覧',company2_path,class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "リクエスト一覧", "#" %>
</li>  
<!--ナビバー右寄せ-->
<div class="navbar-right">
  <li class="nav-item">
    <div class="dropdown">
    	<button class="dropdown-toggle" type="button" data-toggle="dropdown">
    		<%= image_tag college_avater_url(current_college),　class: 'text-center img-circle small-user-img'%>
    		<span class="caret"></span>
    	</button>
    	<ul class="dropdown-menu" role="menu">
    	  <%= link_to("マイページ", college_path(current_college.id) ,class: "nav-link") %>
    	  <%= link_to 'サインアウト',destroy_college_session_path, method: :delete, class: "nav-link" %>
    	</ul>
    </div>
  </li>
</div>

app/views/layouts/_company_navbar.html.erb
<div class="nav-item">
  <%= link_to("マイページ", company_path(current_company.id) ,class: "nav-link") %>
</div>
<!--ナビバー右寄せ-->
<div class="navbar-right">
  <li class="nav-item">
    <div class="dropdown">
    	<button class="dropdown-toggle" type="button" data-toggle="dropdown">
    		<%= image_tag company_avater_url(current_company),class: 'text-center img-circle small-user-img'%>
    		<span class="caret"></span>
    	</button>
    	<ul class="dropdown-menu" role="menu">
    	  <%= link_to("マイページ", company_path(current_company.id) ,class: "nav-link") %>
    	  <%= link_to 'サインアウト',destroy_company_session_path, method: :delete, class: "nav-link" %>
    	</ul>
    </div>
  </li>
</div>

app/views/layouts/_error_messages.html.erb
<% if product.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= product.errors.count %>件の入力ミスがあります。
    </div>
    <ul>
    <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %> text-center">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
		</button>
		<%= link_to "Navbar", root_url %>
		<div class="collapse navbar-collapse">
				<ul class="navbar-nav">
					<% if college_signed_in? %>
						<%= render "layouts/college_navbar", college: @college %>
					<% elsif company_signed_in? %>
						<%= render "layouts/company_navbar", company: @company %>
					<% else %>
						<%= render "layouts/before_navbar"%>
					<% end %>
					<% if current_college || current_company %>
					<li class="nav-item">
						<a href="#" data-toggle="modal" data-target="#sampleModal">
							検索
						</a>
					</li>	
					<% end %>	
					<%= render "layouts/search_modal" %>
				</ul>						
		</div>

</nav>

app/views/layouts/_search_modal.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="sampleModal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
				<h4 class="modal-title">
					<!-- タブ・メニュー -->
					<ul class="nav nav-tabs">
						<div class="row">
							<li class="col-xs-4 active"><a href="#sampleContentA" data-toggle="tab">投稿検索</a></li>
							<li class="col-xs-4"><a href="#sampleContentB" data-toggle="tab">大学検索</a></li>
							<li class="col-xs-4"><a href="#sampleContentC" data-toggle="tab">企業検索</a></li>
						</div>	
					</ul>
				</h4>
			</div>
			<div class="modal-body">
				<!-- タブ内容 -->
				<div class="tab-content">
					<div class="tab-pane active" id="sampleContentA">
						<!--product検索-->
						<%= search_form_for(@q_products, url: search_products_path, html: { method: :post }, as: :q_products)  do |f| %>
            
              <div class="form-group">
                <%= f.label :title_cont, "＜タイトル検索＞" %>
                <%= f.search_field :title_cont, class: "form-control" %>
              </div>
              
              <div class="form-group">
                <%= f.label :content_cont, "＜詳細検索＞" %>
                <%= f.search_field :content_cont, class: "form-control" %>
              </div>
              <div class="action">
              <%= f.submit "この条件で検索する", class: 'btn btn-success btn-xs' %>
              </div>
            <% end %>
					</div>
					<div class="tab-pane" id="sampleContentB">
						<!--college検索-->
						<%= search_form_for(@q_colleges, url: search_colleges_path, html: { method: :post }, as: :q_colleges)  do |f| %>
            
              <div class="form-group">
                <%= f.label :name_cont, "＜大学名検索＞" %>
                <%= f.search_field :name_cont, class: "form-control" %>
              </div>

              <div class="action">
              <%= f.submit "この条件で検索する", class: 'btn btn-success btn-xs' %>
              </div>
            <% end %>
				    </li>
					</div>
					<div class="tab-pane" id="sampleContentC">
						<!--company検索-->
						<%= search_form_for(@q_companies, url: search_companies_path, html: { method: :post }, as: :q_companies)  do |f| %>
            
              <div class="form-group">
                <%= f.label :name_cont, "＜企業名検索＞" %>
                <%= f.search_field :name_cont, class: "form-control" %>
              </div>

              <div class="action">
              <%= f.submit "この条件で検索する", class: 'btn btn-success btn-xs' %>
              </div>
            <% end %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareProduct</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    
    <%= yield %>
  </body>
</html>